server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        return 302 /data_copilot/;
    }

    location /data_copilot/ {
        try_files $uri $uri/ $uri.html =404;
    }
}
